### ISSUE TITLE
No longer works with versions > 1.24 (including the just released June 2018)

### ISSUE THREAD

**Issue by mfour-merickson** [calebporzio/better-phpunit#57] opened 2018-06-28 18:39 UTC
When triggering `Better PHPUnit run` it process if a second or so then displays the `Tasks | Run Tasks...` command

Note:  All works as expected when using regular VSCode, only issue with Insiders build

![image](https://user-images.githubusercontent.com/31225533/42053990-f67f63a4-7ac7-11e8-8c78-aa471bf6fde2.png)

**Comment by mfour-merickson** [comment] 2018-06-28 18:41
When executing the same trigger on Code, the results are as expected

![image](https://user-images.githubusercontent.com/31225533/42054063-33c4b840-7ac8-11e8-9198-d3b5d753c923.png)

**Comment by R3l4x3** [comment] 2018-06-29 06:11
Unfortunately, there is still no solution to the problem, as you can see here #52

**Comment by mikeerickson** [comment] 2018-07-01 05:16
Bummer

**Comment by mfour-merickson** [comment] 2018-07-05 19:39
@R3l4x3 well, now that the June 2018 release is officially out, it has broken this as well (not just isolated to Insiders).   As of 1.25, this plugin no longer works correctly

**Comment by ryanmortier** [comment] 2018-07-06 15:41
Samsies. When I try to run a test I get

![image](https://user-images.githubusercontent.com/2053960/42387778-71a97e4e-8111-11e8-97a8-4728b279dfdb.png)

**Comment by calebporzio** [comment] 2018-07-09 14:00
looking into this ASAP - hold tight

**Comment by calebporzio** [comment] 2018-07-09 14:58
Ok, I can't figure it out on my own.

I opened an issue and will keep checking for updates. Sorry about this:
https://github.com/Microsoft/vscode/issues/53879

**Comment by mfour-merickson** [comment] 2018-07-09 18:10
Thank you for finally looking into this issue.  Hopefully, you get some response, as it is the extension is rendered useless for anybody using Code 1.25 or greater.

**Comment by shjohnson-pi** [comment] 2018-07-09 19:12
I think I fixed my local copy by editing package.json and adding `taskDefinitions` right after `problemMatchers` as part of `contributes`. (And adding the necessary comma between)
```json
    "problemMatchers": [
        {
            "name": "phpunit",
            "owner": "php",
            "fileLocation": "absolute",
            "pattern": [
                {
                    "regexp": "^\\d+\\)\\s.*$"
                },
                {
                    "regexp": "^(.*)$",
                    "message": 1
                },
                {
                    "regexp": "^(.*):(\\d+)$",
                    "file": 1,
                    "location": 2
                }
            ]
        }
    ],
    "taskDefinitions": [
        {
            "type": "phpunit",
            "required": [
                "task"
            ],
            "properties": {
                "task": {
                    "type": "string",
                    "description": "the task to execute"
                }
            }
        }
    ]
},
"scripts": {
    "postinstall": "node ./node_modules/vscode/bin/install",
    "test
```
(Task Definition from the bug report you created for vscode)
Does this work for you? @calebporzio 
I'm using Better PHPUnit 0.8.0 directly from vscode 1.25.0 on Linux.

**Comment by calebporzio** [comment] 2018-07-09 20:39
Really? that works for you? Hmm, that doesn't work for me shoot...

Can someone else try adding that?

**Comment by mikeerickson** [comment] 2018-07-09 20:43
Which `package.json` file are you editing (I assume you mean the one in application folder) I am on macOS

**Comment by shjohnson-pi** [comment] 2018-07-09 20:52
@mikeerickson Yes, I think there's only one `package.json` file. I'm not familiar with mac. I did have to do the `Reload Window` command a couple times to reload the extension.

**Comment by soldatigabriele** [comment] 2018-07-09 21:14
@shjohnson-pi 's solution works for me.

**Comment by R3l4x3** [comment] 2018-07-10 05:56
Yeah, same here. With this code in `package.json` it's working!

**Comment by iuliansafta** [comment] 2018-07-10 06:28
Same here. I can confirm it's working with @shjohnson-pi 's code in package.json. I had to `Reload Window` couple of times though.

**Comment by JulianMar** [comment] 2018-07-10 09:07
I created #58 to fix this for all users.
Thank you @shjohnson-pi!
@calebporzio can you merge my PR?

**Comment by calebporzio** [comment] 2018-07-10 13:16
All set! pushed the fix this morning: be sure to "reload" the extension to get the upgrade!! Thanks everyone!

**Closed by calebporzio** 2018-07-10 13:16 UTC

**Comment by mfour-merickson** [comment] 2018-07-10 15:39
Awesome!  Nice morning wakeup surprise.  I too will confirm that it works with the latest Code release (v1.25) AND for good measures, I have tested it against the latest Insiders release (v1.26) which was downloaded this morning.

Thanks to all who made this happen, I greatly appreciate it!

@calebporzio @shjohnson-pi et al

**Comment by mfour-merickson** [comment] 2018-07-10 15:45
Today is going to be a good day!  Better PHPUnit is working again with Code, and my first big run of the morning, all tests are green!

![image](https://user-images.githubusercontent.com/31225533/42521394-9475df12-841d-11e8-9a0e-e0ff2edc4117.png)

**Comment by calebporzio** [comment] 2018-07-10 15:56
hahah - what a good feeling!
