### ISSUE TITLE
output not being displayed in debug console even though the test was a success

### ISSUE THREAD

**Issue by filtration** [calebporzio/better-phpunit#15] opened 2017-11-17 20:59 UTC
I am using the latest Vscode package, when I run the command the cmd window pops up, runs the test then quickly closes, like so:

<img src="https://i.imgur.com/a64QLoc.gif">

As you can see, now output of the test has been displayed in the debug section, and there are no problems as show here:

<img src="https://i.imgur.com/zfpHROc.png">

When I slowed down the video to see the cmd output, it shows it there:

<img src="https://i.imgur.com/XJ6J02S.png">

**Comment by calebporzio** [comment] 2017-11-17 21:30
That's odd, what happens if you run the command (the `c:/../vendor/bin/phpunit etc..` command that shows up in the terminal window after you run better phpunit) directly in the terminal?

In other words, manually copy and paste the command into the terminal to see if that weird behavior still happens

**Comment by filtration** [comment] 2017-11-17 22:36
Hi, I get the expected result:

<img src="https://i.imgur.com/O8WIzKB.png">

**Comment by spyric** [comment] 2017-11-18 08:14
Hello @filtration and @calebporzio I found issue and tempworkaround.

@filtration when you execute same command `c:\\wamp64\\www\\altcoin\\vendor\\bin\\phpunit c:\wamp64\www\altcoin\tests\Feature\ExampleTest.php --filter '^.*::testbeBasicTest$'` in termanal VS Code you will get same result as from running from plugin.

I found one interested thing. You will get the same result if you're run same command in PowerShell, that is default value in config `terminal.integrated.shell.windows` you will get same result.

If you change `terminal.integrated.shell.windows` to `C:\\WINDOWS\\System32\\cmd.exe` You will get output in native VS code terminal. but you will not have any colors in console output and error highlighting like in that screenshot

![image](https://user-images.githubusercontent.com/2044754/32978352-55aa2f40-cc62-11e7-9aed-415367664fd7.png)

**Comment by calebporzio** [comment] 2017-11-18 20:37
@spyric Ok, right now, I don't think I want to use `phpunit/phpunit/phpunit` instead of `vendor/bin/phpunit`. So I think we should stick with the shell setting solution.

Is everything good now @filtration?

I'd be willing to add a "custom phpunit executable" config option - let me know if that seems necessary.

**Comment by filtration** [comment] 2017-11-19 00:40
Yep, changing the powershell to windows fixed the issue, but as @spyric mentions, there's no colour, plus we're limited with cmd rather than  powershell. Adding a config option of a custom phpunit location (in my case just: phpunit (global) would be greate

**Comment by calebporzio** [comment] 2017-12-03 19:50
Hey @filtration - I just added a config option called `phpunitBinary` in the latest version (0.4.1)

Check it out and let me know if this solves your problem - thanks!

**Comment by creativeworkx** [comment] 2017-12-04 21:51
Hey @calebporzio ,
I have just set phpunitBinary in version 0.4.1 to the phpunit.

If I run a dummy test, VERY briefly a cmd (not powershell, regular cmd) will open, run the test and closes itself immediately.
So, unfortunately after updating to 0.4.1 I am still having the exact same issue as @filtration.

**Comment by creativeworkx** [comment] 2017-12-04 22:18
Actually, this might not be related to your extension at all @calebporzio.

If I run the following in powershell:
<path to phpunit> <path to test file>ExampleTest.php
the exact same thing happens: a cmd opens, it is run and immediately closed.

If I run the following in cmd itself:
<path to phpunit> <path to test file>ExampleTest.php
everything just works fine!

Note, that it seems to be completely unaffected by Visual Studio Code or the extension, as for me, this is reproducible with Visual Studio Code being closed.

**Comment by calebporzio** [comment] 2017-12-09 20:27
Great, I'm closing this for now unless you can think of something this extension can do to help the problem, but it sounds like it's outside of the extension - thanks!

**Closed by calebporzio** 2017-12-09 20:27 UTC

**Comment by ben182** [comment] 2018-02-22 23:31
Hey, maybe we can improve the docs to explain this issue with powershell. At least that would have helped me.

**Comment by calebporzio** [comment] 2018-02-28 16:55
@ben182 - mind submitting a PR?
